// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg8kWCD4f_sqJBq9p9GcGnfpvF-F2wrI4',
    appId: '1:764895465586:web:d48b4bed5f40d6978af2eb',
    messagingSenderId: '764895465586',
    projectId: 'crud-app-ab0eb',
    authDomain: 'crud-app-ab0eb.firebaseapp.com',
    storageBucket: 'crud-app-ab0eb.firebasestorage.app',
    measurementId: 'G-JR021R1W9Y',
    databaseURL: 'https://crud-app-ab0eb-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnWYK0SqBA08UdyoFXj18g8XsQtrWOIXU',
    appId: '1:764895465586:android:59a0bbddca7d646c8af2eb',
    messagingSenderId: '764895465586',
    projectId: 'crud-app-ab0eb',
    storageBucket: 'crud-app-ab0eb.firebasestorage.app',
    databaseURL: 'https://crud-app-ab0eb-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjRRaYSGQFWd1CGjHUwSMuzDOQK9lIOOk',
    appId: '1:764895465586:ios:28c0561dbe4e8c608af2eb',
    messagingSenderId: '764895465586',
    projectId: 'crud-app-ab0eb',
    storageBucket: 'crud-app-ab0eb.firebasestorage.app',
    iosClientId: '764895465586-14dh7tmsan9vasojvpgquvvgidc3sqhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
    databaseURL: 'https://crud-app-ab0eb-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjRRaYSGQFWd1CGjHUwSMuzDOQK9lIOOk',
    appId: '1:764895465586:ios:28c0561dbe4e8c608af2eb',
    messagingSenderId: '764895465586',
    projectId: 'crud-app-ab0eb',
    storageBucket: 'crud-app-ab0eb.firebasestorage.app',
    iosClientId: '764895465586-14dh7tmsan9vasojvpgquvvgidc3sqhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
    databaseURL: 'https://crud-app-ab0eb-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg8kWCD4f_sqJBq9p9GcGnfpvF-F2wrI4',
    appId: '1:764895465586:web:8380c7d37c42967d8af2eb',
    messagingSenderId: '764895465586',
    projectId: 'crud-app-ab0eb',
    authDomain: 'crud-app-ab0eb.firebaseapp.com',
    storageBucket: 'crud-app-ab0eb.firebasestorage.app',
    measurementId: 'G-2EYR6205WF',
    databaseURL: 'https://crud-app-ab0eb-default-rtdb.firebaseio.com',
  );

}